### ISSUE TITLE
Open contract after a transaction that creates a new contract

### ISSUE THREAD

**Issue by behrang** [ton-community/sandbox#10]
I've created a parent/child contract, something like the Jetton fungible tokens. Now, to test it, I've created a wrapper for Parent and another for Child. In my tests, I've opened the parent contract with `openContract` and after sending it a message, now I want to call a getter function on the Child (written in wrapper). How should I do it?

If I try to call `openContract` with a `Child.createFromAddress`, it creates a new empty uninitialized contract.

I expect to be able to open the child contract using `openContract`. Am I missing something here?

**Comment by krigga** [comment]
It should be working as you described, and in fact it does in this example https://github.com/ton-community/sandbox/blob/22a0d88077a06755492f4cdabcd23f66ac85aa29/examples/nft-sale/Sale.spec.ts#L35 (in this example sandbox is of an older version, but I checked with the latest one too - seems to be working).

It would be great if you could provide a specific code example where such behavior does not work.

**Comment by behrang** [comment]
My stupid mistake. After wasting long hours on it, finally I enabled VM logs, and found out that the code of child was wrong. I checked the child code and found that I was mistakenly compiling parent code for child too.

Thanks for the example. Helped me stop being suspicious about sandbox code.
