### ISSUE TITLE
Change data cell of opened contracts

### ISSUE THREAD

**Issue by behrang** [ton-community/sandbox#16]
Is there any way to change data cell of contracts after they are opened?

When a parent smart contract deploys a child, the address is based on the init data. I want to be able to change data of the smart contract to another cell, otherwise I'd have to send many transactions to parent and/or child to change its data cell, ready for my test case.

I tried to create an instance of the child with the data that I wanted, but I can't deploy it.

**Comment by krigga** [comment]
Here's an example from the tests https://github.com/ton-community/sandbox/blob/main/src/blockchain/Blockchain.spec.ts#L59-L64

Please tell if this works for your case

**Comment by behrang** [comment]
It worked correctly. Thanks for the hint.
