### ISSUE TITLE
Get debug logs from a getter programatically

### ISSUE THREAD

**Issue by talkol** [ton-community/sandbox#22]
Currently it's only possible to programatically get the debug logs from transactions.
This is quite useful for expectations.
It will also be nice to have the same ability with getters.
This is not that easy because I'm not sure we have where to return them on, but it's worth brainstorming.

**Comment by krigga** [comment]
If you meant get methods, then they have logs returned as well. If not, I didn't fully understand you.

**Comment by talkol** [comment]
Yes, you're correct, I missed

```
export type ContractGetMethodResult = {
    stack: TupleReader;
    gasUsed?: Maybe<bigint>;
    logs?: Maybe<string>;
};
```

**Comment by krigga** [comment]
That's not the return type used in sandbox

**Comment by talkol** [comment]
Yes, that's ton-core, which the wrapper class is importing which is always a bit confusing
