### ISSUE TITLE
Exit code -14 returned as 4294967282

### ISSUE THREAD

**Issue by talkol** [ton-community/sandbox#23]
Assume you have a contract that has a loop from 0 to 2^64, it dies on out of gas.

```
transaction.description.computePhase.exitCode == 4294967282
```

It should be `-14` per https://ton.org/docs/learn/tvm-instructions/tvm-exit-codes

**Comment by krigga** [comment]
I believe this is a bug in ton-core, not sandbox
In TL-B schema, `exit_code` is `int32` https://github.com/ton-blockchain/ton/blob/24dc184a2ea67f9c47042b4104bbb4d82289fac1/crypto/block/block.tlb#L302 but ton-core reads it as `uint32` https://github.com/ton-core/ton-core/blob/8dff175691823bfd0b6cd90300bb74860f740503/src/types/TransactionComputePhase.ts#L66
Please reopen if I'm mistaken
