### ISSUE TITLE
Allow debug logs to be queried programatically

### ISSUE THREAD

**Issue by talkol** [ton-community/sandbox#4]
**Is your feature request related to a problem? Please describe.**
I have a contract with debug logs (`strdump` and `dump`). Right now the only way to consume the logs is by looking at them since they are printed with `console.warn`. It will be useful to consume them programatically too so we can set expectations on them in tests.

**Describe the solution you'd like**
Maybe add logs to the result object where we get the transactions after making some action.

Maybe we should support this for all logs, not just debug ones.

**Comment by krigga** [comment]
Fixed by the mentioned PR, fix released in v0.5.0
