### ISSUE TITLE
External messages - accept_message seems to cause silent failures

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/sandbox#7]
**Describe the bug**
External messages - `accept_message` seems to cause silent failures

**To Reproduce**
```
;; This will throw an error, as expected (assuming the slice doesn't in fact contain a ref)
() recv_external(slice in_msg) impure {
  var x = in_msg~load_ref();
  accept_message();
  ~dump x; ;; Without this line, error doesn't get thrown
}

;; This will NOT throw an error
() recv_external(slice in_msg) impure {
  accept_message();
  var x = in_msg~load_ref();
  ~dump x;
}
```

**Expected behavior**
I'd expect:
1. Error to be thrown upon loading of the ref (9: cell underflow), regardless of whether we're using the value (using `~dump`, `send_raw_message`, etc.)
2. Error to be thrown regardless of message having been accepted.

**Actual behavior**
Error is thrown only if the loading which causes the underflow happens before accepting the message.

**System information**
- Package version: 0.4.0
- Node version: v16.15.0
- OS name and version: Mac OS M1 Ventura 13.0

**Additional context**

**Comment by EmelyanenkoK** [comment]
It is funC related behavior, not TVM/sandbox.
The thing is that `load_ref` is considered pure (while actually it can be impure if throw exception). In other words funC drops load_ref operation if result is not used:
Both
```
;; This will throw an error, as expected (assuming the slice doesn't in fact contain a ref)
() recv_external(slice in_msg) impure {
  var x = in_msg~load_ref();
  accept_message();
  ~dump x; ;; Without this line, error doesn't get thrown
}
```
and
```
;; This will NOT throw an error
() recv_external(slice in_msg) impure {
  accept_message();
  var x = in_msg~load_ref();
  ~dump x;
}
```
will compile to
```
recv_external PROC:<{
  DROP
  ACCEPT
}>
```

**Comment by shaharyakir** [comment]
This explains why the error isn't thrown when the loaded ref isn't used.

But in this case:
```
() recv_external(slice in_msg) impure {
  accept_message();
  var x = in_msg~load_ref();
  ~dump x;
}
```

The value is used. Shouldn't an error be thrown then?

**Comment by EmelyanenkoK** [comment]
```
() recv_external(slice in_msg) impure {
  accept_message();
  var x = in_msg~load_ref();
  ~dump x;
}
```
compiles to
```
recv_external PROC:<{
  ACCEPT
  LDREF
  DROP
  s0 DUMP
  DROP
}>
```
so yes, I'm expecting failed transaction in this case

**Comment by krigga** [comment]
> This explains why the error isn't thrown when the loaded ref isn't used.
> 
> But in this case:
> 
> ```
> () recv_external(slice in_msg) impure {
>   accept_message();
>   var x = in_msg~load_ref();
>   ~dump x;
> }
> ```
> 
> The value is used. Shouldn't an error be thrown then?

With this code, I'm getting exit code 9 (to be expected). Do you get the same result?

**Comment by shaharyakir** [comment]
I'll check, it was probably a misunderstanding of mine of how errors work before and after accepting messages. will test and close the issue afterwards.
