### ISSUE TITLE
Add ability to assert on exit codes and transaction success

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/sandbox#8]
**Is your feature request related to a problem? Please describe.**
Some tests expect a failure with a specific exit code. 
Currently it seems that for:
1. External -> an error with no details about exit code is thrown
2. Internal -> no error is raised, exit code is contained in the `transactions` array in the result

**Describe the solution you'd like**
- Ideally, external and internal should behave the same
- Exit code should be returned in both cases (currently for internal messages it would be that of the 2nd message in `transactions` because the first one is the external message).
- There should be test matchers to set expectations on exit codes

**Describe alternatives you've considered**

**Additional context**

**Comment by EmelyanenkoK** [comment]
Regarding test matchers for exit codes, I use the following
```
expect(transactions).toHaveTransaction({
            exitCode: 777
        })
```
(usually I also specify exact account on which exit should happen)

**Comment by shaharyakir** [comment]
Sounds good to me.
