### ISSUE TITLE
Be able to specify non-default balance for treasury account

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/sandbox#9]
**Is your feature request related to a problem? Please describe.**
It can be helpful for some tests to initialize a treasury with a certain balance (for example 0) and then assert that the balance grows after issuing some transaction.

**Describe the solution you'd like**
Add a parameter to `Blockchain.treasury()` allowing to specify a balance

**Describe alternatives you've considered**

**Additional context**

**Comment by krigga** [comment]
Looks like a good idea, will likely be added in the next release
